# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_studentinfo_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ['fio']},
        ),
    ]
