# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-16 16:33
from __future__ import unicode_literals

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='отчество')),
                ('group', models.CharField(max_length=10, verbose_name='группа')),
                ('course', models.PositiveIntegerField(default=1, verbose_name='курс')),
                ('room', models.CharField(blank=True, max_length=32, verbose_name='комната')),
                ('sex', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='пол')),
                ('is_staff', models.BooleanField(default=False, verbose_name='персонал?')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
