# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='отчество')),
                ('group', models.CharField(blank=True, max_length=10, verbose_name='группа')),
                ('course', models.PositiveIntegerField(blank=True, null=True, verbose_name='курс')),
                ('room', models.CharField(blank=True, max_length=32, verbose_name='комната')),
                ('sex', models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='пол')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('vk_url', models.URLField(blank=True, verbose_name='ссылка на профиль ВК')),
            ],
            options={
                'verbose_name': 'данные студента',
                'verbose_name_plural': 'данные студентов',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=10, verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=10, verbose_name='пол'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
