# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-09 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190416_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mifare_pass',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='код пропуска'),
        ),
    ]
