# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cls', models.IntegerField(choices=[(1, 'Обновление'), (2, 'Смена ответственного'), (3, 'Изменение статуса'), (4, 'Запрос сведений'), (5, 'Создание обращения')], default=1, verbose_name='Класс')),
                ('info', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Информация')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='feedback/', verbose_name='Изображение')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senate.Event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('status', models.IntegerField(choices=[(1, 'Открыто'), (2, 'Закрыто'), (3, 'Инициатива одобрена'), (4, 'Инициатива отклонена')], default=1, verbose_name='Статус')),
                ('add_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_event', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Последняя активность')),
                ('close_dttm', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата закрытия')),
                ('want_to_help', models.BooleanField(default=False, verbose_name='Хочу помогать')),
                ('assigned_dept', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Ответственный отдел')),
                ('assigned_worker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_worker', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senate.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senate.Issue', verbose_name='Обращение'),
        ),
        migrations.AddField(
            model_name='event',
            name='new_dept',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Новый отдел'),
        ),
        migrations.AddField(
            model_name='event',
            name='new_worker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_worker', to=settings.AUTH_USER_MODEL, verbose_name='Новый сотрудник'),
        ),
    ]
