# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senate', '0003_auto_20170920_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='new_status',
            field=models.IntegerField(choices=[(1, 'Открыто'), (2, 'Закрыто'), (3, 'Инициатива одобрена'), (4, 'Инициатива отклонена')], default=2, verbose_name='Новый статус'),
        ),
    ]
