# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senate', '0006_auto_20170921_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Открыто'), (2, 'Закрыто'), (3, 'Инициатива одобрена'), (4, 'Инициатива отклонена')], default=None, null=True, verbose_name='Новый статус'),
        ),
    ]
