# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senate', '0007_auto_20170921_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='want_to_help',
            field=models.BooleanField(default=False, verbose_name='Готов участвовать в реализации'),
        ),
    ]
