# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senate', '0008_auto_20170921_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='senate.Issue', verbose_name='Обращение'),
        ),
    ]
