# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senate', '0012_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='importance',
            field=models.IntegerField(default=1, verbose_name='Значимость'),
        ),
    ]
