# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senate', '0014_auto_20170929_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Показывать всем'),
        ),
    ]
