# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senate', '0015_category_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdocument',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='senate.Event', verbose_name='Событие'),
        ),
    ]
