# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170927_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_django_template',
            field=models.BooleanField(default=False, verbose_name='Шаблон Django'),
        ),
    ]
