# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=800, verbose_name='Текст ответа')),
                ('votes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('begin_date', models.DateTimeField(verbose_name='Начало голосования')),
                ('end_date', models.DateTimeField(verbose_name='Конец голосования')),
                ('target_room', models.CharField(default='^', max_length=200, verbose_name='Целевая комната')),
                ('target_group', models.CharField(default='^', max_length=200, verbose_name='Целевая группа')),
                ('public', models.BooleanField(default=True, verbose_name='Открытое голосование')),
                ('answer_type', models.CharField(choices=[('ONE', 'Выбор одного варианта'), ('MANY', 'Выбор нескольких вариантов'), ('OWN', 'Свой вариант')], default='ONE', max_length=10, verbose_name='Тип ответа')),
                ('choices_order', models.CharField(choices=[('created', 'В порядке добавления'), ('?', 'В случайном порядке')], default='created', max_length=10, verbose_name='Порядок вариантов ответа')),
                ('times_mailed', models.IntegerField(blank=True, default=0)),
                ('last_mailing', models.DateTimeField(null=True, verbose_name='Последняя рассылка')),
                ('poll_type', models.CharField(choices=[('WITHOUT_TARGET_LIST', 'WITHOUT TARGET LIST'), ('TARGET_LIST', 'TARGET LIST')], default='WITHOUT_TARGET_LIST', max_length=30, verbose_name='Тип голосования')),
                ('only_for_staff', models.BooleanField(default=False)),
                ('voted_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='poll',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user_information',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.StudentInfo'),
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
