# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171017_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Обязательный вопрос'),
        ),
    ]
