# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:46
from __future__ import unicode_literals

import cycle_storage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, default='Неизвестно', max_length=255, null=True, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, default='Неизвестно', max_length=255, null=True, verbose_name='Модель')),
                ('add_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Publish datetime')),
                ('photo', models.ImageField(upload_to=cycle_storage.models.bike_photo_path, verbose_name='Фотография')),
                ('verified', models.BooleanField(default=False, verbose_name='Данные верифицированы')),
                ('request_status', models.IntegerField(choices=[(1, 'Заявка рассматривается'), (2, 'Одобрено'), (3, 'Отказано'), (4, 'Нет мест')], default=1, verbose_name='Статус заявки')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'велосипед',
                'verbose_name_plural': 'велосипеды',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Место')),
                ('bicycle', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycle_storage.Bicycle', verbose_name='Велосипед')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm', models.CharField(blank=True, default='Общежитие №6', max_length=255, null=True, verbose_name='Расположение')),
                ('name', models.CharField(default='Велокомната 6ки', max_length=255, verbose_name='Название хранилища')),
            ],
            options={
                'verbose_name': 'велохранилище',
                'verbose_name_plural': 'велохранилища',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle_storage.Storage'),
        ),
    ]
