# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_storage', '0002_auto_20170921_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='info',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Доп. описание'),
        ),
    ]
