# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_storage', '0003_bicycle_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicycle',
            options={'ordering': ['owner'], 'verbose_name': 'велосипед', 'verbose_name_plural': 'велосипеды'},
        ),
    ]
