# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0009_aiddocument_is_application_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiddocument',
            name='is_image',
            field=models.BooleanField(default=False, verbose_name='Является изображением'),
        ),
    ]
