# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0010_aiddocument_is_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='paid_with_cash',
            field=models.BooleanField(default=False, verbose_name='заплатили наличными'),
        ),
    ]
