# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0011_aidrequest_paid_with_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='reason',
            field=models.TextField(max_length=2048, verbose_name='Причина'),
        ),
    ]
