# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fin_aid', '0012_auto_20170928_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrequest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Заявление проверено'),
        ),
        migrations.AddField(
            model_name='category',
            name='activists_only',
            field=models.BooleanField(default=False, verbose_name='Только для активистов'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_to_students',
            field=models.BooleanField(default=True, verbose_name='Показывать студентам'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='paid_with_cash',
            field=models.BooleanField(default=False, verbose_name='Заплатили наличными'),
        ),
    ]
