# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0013_auto_20171008_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_aid.Category', verbose_name='Категория'),
        ),
    ]
