# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0014_auto_20171008_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='activists_only',
        ),
        migrations.AddField(
            model_name='category',
            name='is_senate',
            field=models.BooleanField(default=False, verbose_name='Сенатская'),
        ),
    ]
