# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0014_auto_20171014_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlydata',
            old_name='student_dealine_dt',
            new_name='student_deadline_dt',
        ),
    ]
