# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import fin_aid.models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0015_auto_20171014_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydata',
            name='student_deadline_dt',
            field=models.DateField(default=fin_aid.models._get_default_deadline_dt, verbose_name='Дэдлайн по заявлениям'),
        ),
    ]
