# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0016_auto_20171014_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Заявление рассматривается'), (2, 'Заявление одобрено'), (3, 'В заявлении отказано'), (4, 'Необходимо уточнить данные'), (5, 'Предварительно одобрено')], default=1, verbose_name='Статус заявления'),
        ),
    ]
