# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fin_aid', '0017_auto_20171031_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'стипендиаты',
                'verbose_name_plural': 'стипендии',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('frequency', models.IntegerField(choices=[(1, 'Раз в месяц'), (2, 'Раз в семестр'), (3, 'Раз в год')], default=1, verbose_name='Частота выплат')),
            ],
            options={
                'verbose_name': 'стипендиаты',
                'verbose_name_plural': 'стипендии',
            },
        ),
        migrations.AddField(
            model_name='scholar',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_aid.Scholarship', verbose_name='Стипендия'),
        ),
        migrations.AddField(
            model_name='scholar',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
