# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0018_auto_20171101_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholar',
            options={'verbose_name': 'стипендиат', 'verbose_name_plural': 'стипендиаты'},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name': 'стипендия', 'verbose_name_plural': 'стипендии'},
        ),
    ]
