# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fin_aid', '0019_auto_20171101_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.StudentInfo', verbose_name='Студент'),
        ),
    ]
