# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 12:35
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'активист',
                'verbose_name_plural': 'активисты',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('slug', models.SlugField()),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=2048, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'отдел Сената',
                'verbose_name_plural': 'отделы Сената',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='описание')),
                ('is_open', models.BooleanField(default=False, verbose_name='открыта?')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='departments.Department', verbose_name='отдел')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='departments.Position', verbose_name='должность')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
            },
        ),
        migrations.AddField(
            model_name='activist',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='отдел'),
        ),
        migrations.AddField(
            model_name='activist',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Position', verbose_name='должность'),
        ),
        migrations.AddField(
            model_name='activist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
