# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20170904_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationssettings',
            name='last_allow_vk_reminder',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Просили включить уведомления ВК'),
        ),
    ]
